# Generated by Django 4.2.9 on 2026-06-07 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('total_score', models.FloatField(default=0.0)),
                ('logical_reasoning_score', models.FloatField(default=0.0)),
                ('programming_aptitude_score', models.FloatField(default=0.0)),
                ('mathematical_thinking_score', models.FloatField(default=0.0)),
                ('problem_solving_score', models.FloatField(default=0.0)),
                ('communication_score', models.FloatField(default=0.0)),
                ('creativity_score', models.FloatField(default=0.0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
