# Generated by Django 4.2.16 on 2026-06-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='questions_used',
            field=models.JSONField(default=list),
        ),
    ]
